# Generated by Django 5.2.3 on 2025-11-07 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0006_remove_church_qr_code_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('notification_type', models.CharField(choices=[('new_visitor', 'Novo Visitante'), ('visitor_converted', 'Visitante Convertido'), ('new_member', 'Novo Membro'), ('member_transferred', 'Membro Transferido'), ('member_status_changed', 'Status de Membro Alterado'), ('profile_updated', 'Perfil Atualizado'), ('avatar_updated', 'Avatar Atualizado'), ('password_changed', 'Senha Alterada'), ('system_alert', 'Alerta do Sistema')], db_index=True, help_text='Tipo de notificação', max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(help_text='Título breve da notificação', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Conteúdo detalhado da notificação', max_length=500, verbose_name='Mensagem')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Indica se a notificação foi lida', verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, help_text='Data e hora em que foi lida', null=True, verbose_name='Lida em')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON (IDs relacionados, etc.)', verbose_name='Metadados')),
                ('action_url', models.CharField(blank=True, help_text='URL para redirecionar ao clicar na notificação', max_length=500, null=True, verbose_name='URL de Ação')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='medium', help_text='Nível de prioridade da notificação', max_length=10, verbose_name='Prioridade')),
                ('church', models.ForeignKey(help_text='Igreja no contexto da notificação', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='churches.church', verbose_name='Igreja')),
                ('user', models.ForeignKey(help_text='Usuário que receberá a notificação', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_notifications', 'Pode ver todas as notificações'), ('can_send_bulk_notifications', 'Pode enviar notificações em massa')],
                'indexes': [models.Index(fields=['user', 'church', '-created_at'], name='notificatio_user_id_bb6b1a_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['church', 'notification_type', '-created_at'], name='notificatio_church__755c3c_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx')],
            },
        ),
    ]
