# Generated by Django 5.2.3 on 2025-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Gênero do visitante', max_length=1, null=True, verbose_name='Gênero'),
        ),
    ]
