# Generated by Django 5.2.3 on 2025-07-20 17:54

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_total_visitors_registered'),
        ('churches', '0001_initial'),
        ('members', '0002_alter_member_gender'),
        ('visitors', '0002_alter_visitor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorfollowup',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='visitorfollowup',
            name='visitor',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_church__94db52_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_branch__f210ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_status_9b5b9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_convert_e27703_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_follow__52d788_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_email_e17823_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_phone_3827a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitors_vi_next_co_491dca_idx',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='accept_email_contact',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='accept_phone_contact',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='accept_whatsapp_contact',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='follow_up_needed',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='how_found_church',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_visit_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='next_contact_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='registration_ip',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visits_count',
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='contact_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de Contato'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_visit',
            field=models.BooleanField(default=True, verbose_name='Primeira Visita'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='follow_up_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('contacted', 'Contatado'), ('interested', 'Interessado'), ('not_interested', 'Não Interessado'), ('converted', 'Convertido')], default='pending', max_length=20, verbose_name='Status do Follow-up'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('other', 'Outro')], default='single', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='ministry_interest',
            field=models.TextField(blank=True, verbose_name='Interesse em Ministérios'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='neighborhood',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='qr_code_used',
            field=models.UUIDField(blank=True, null=True, verbose_name='QR Code Utilizado'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='registration_source',
            field=models.CharField(default='qr_code', max_length=20, verbose_name='Fonte do Cadastro'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='state',
            field=models.CharField(default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='wants_growth_group',
            field=models.BooleanField(default=False, verbose_name='Interesse em Grupo de Crescimento'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='wants_prayer',
            field=models.BooleanField(default=False, verbose_name='Quer Oração'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='branches.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='churches.church', verbose_name='Igreja'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conversão'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='conversion_notes',
            field=models.TextField(blank=True, verbose_name='Notas da Conversão'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='converted_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_origin', to='members.member', verbose_name='Membro Convertido'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='converted_to_member',
            field=models.BooleanField(default=False, verbose_name='Convertido para Membro'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[apps.core.models.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Contato'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['church', 'branch'], name='visitors_vi_church__ffc8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['church', 'converted_to_member'], name='visitors_vi_church__a2e82b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['qr_code_used'], name='visitors_vi_qr_code_992382_idx'),
        ),
        migrations.DeleteModel(
            name='VisitorFollowUp',
        ),
    ]
