# Generated by Django 5.2.3 on 2025-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_visitorfollowup_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='zipcode',
            field=models.CharField(default='', help_text='CEP no formato XXXXX-XXX', max_length=10, verbose_name='CEP'),
        ),
    ]
