# Generated by Django 5.2.3 on 2025-07-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_add_zipcode_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.CharField(default='', help_text='Rua, número, complemento', max_length=200, verbose_name='Endereço'),
        ),
    ]
