# Generated by Django 5.2.3 on 2025-11-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_add_branch_created_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visitor',
            new_name='visitors_vi_branch__96de7c_idx',
            old_name='visitors_bra_created_idx',
        ),
    ]
