# Generated by Django 5.2.3 on 2025-10-12 20:05

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, validators=[apps.core.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
