# Generated by Django 5.1.4 on 2025-06-12 00:01

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("denominations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo da igreja",
                        max_length=200,
                        verbose_name="Nome da Igreja",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Nome popular ou abreviado",
                        max_length=100,
                        verbose_name="Nome Fantasia",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da igreja, missão, história",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-mail oficial da igreja",
                        max_length=254,
                        verbose_name="E-mail principal",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Telefone no formato (XX) XXXXX-XXXX",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefone deve estar no formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX",
                                regex="^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Site da igreja", verbose_name="Website"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Endereço completo da sede", verbose_name="Endereço"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "state",
                    models.CharField(
                        help_text="Sigla do estado (ex: SP, RJ, MG)",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        help_text="CEP no formato XXXXX-XXX",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve estar no formato: XXXXX-XXX",
                                regex="^\\d{5}-\\d{3}$",
                            )
                        ],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ da igreja (se aplicável)",
                        max_length=18,
                        null=True,
                        unique=True,
                        validators=[apps.core.models.validate_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo da igreja",
                        null=True,
                        upload_to="churches/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem para banner/capa",
                        null=True,
                        upload_to="churches/covers/",
                        verbose_name="Imagem de Capa",
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("basic", "Básico"),
                            ("professional", "Profissional"),
                            ("enterprise", "Enterprise"),
                            ("denomination", "Denominação"),
                        ],
                        default="basic",
                        help_text="Plano SaaS contratado",
                        max_length=20,
                        verbose_name="Plano de Assinatura",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("expired", "Expirada"),
                            ("cancelled", "Cancelada"),
                            ("suspended", "Suspensa"),
                            ("trial", "Período de teste"),
                        ],
                        default="trial",
                        help_text="Status atual da assinatura",
                        max_length=20,
                        verbose_name="Status da Assinatura",
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data de início da assinatura",
                        verbose_name="Início da Assinatura",
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateTimeField(
                        help_text="Data de vencimento da assinatura",
                        verbose_name="Fim da Assinatura",
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de fim do trial gratuito",
                        null=True,
                        verbose_name="Fim do Período de Teste",
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Máximo de membros permitidos no plano",
                        verbose_name="Limite de Membros",
                    ),
                ),
                (
                    "max_branches",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Máximo de filiais permitidas no plano",
                        verbose_name="Limite de Filiais",
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Total de Membros",
                    ),
                ),
                (
                    "total_visitors",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Total de Visitantes",
                    ),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        blank=True,
                        help_text="Denominação à qual esta igreja pertence (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churches",
                        to="denominations.denomination",
                        verbose_name="Denominação",
                    ),
                ),
                (
                    "main_pastor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pastor responsável pela igreja",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pastored_churches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pastor Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Igreja",
                "verbose_name_plural": "Igrejas",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="churches_ch_name_ce9156_idx"),
                    models.Index(
                        fields=["denomination"], name="churches_ch_denomin_074d35_idx"
                    ),
                    models.Index(
                        fields=["state", "city"], name="churches_ch_state_c80f3d_idx"
                    ),
                    models.Index(
                        fields=["subscription_plan"],
                        name="churches_ch_subscri_aecd86_idx",
                    ),
                    models.Index(
                        fields=["subscription_status"],
                        name="churches_ch_subscri_19d20c_idx",
                    ),
                    models.Index(
                        fields=["subscription_end_date"],
                        name="churches_ch_subscri_ab00d6_idx",
                    ),
                ],
            },
        ),
    ]
