# Generated by Django 5.2.3 on 2025-09-05 23:31

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da igreja (se aplicável)', max_length=18, null=True, validators=[apps.core.models.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
