# Generated by Django 5.2.3 on 2025-10-12 19:53

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Gera UUIDs únicos para igrejas existentes"""
    Church = apps.get_model('churches', 'Church')
    for church in Church.objects.all():
        church.qr_code_uuid = uuid.uuid4()
        church.save(update_fields=['qr_code_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_alter_church_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='allows_visitor_registration',
            field=models.BooleanField(default=True, help_text='Permitir que visitantes se registrem via QR Code', verbose_name='Permite Registro de Visitantes'),
        ),
        migrations.AddField(
            model_name='church',
            name='qr_code_active',
            field=models.BooleanField(default=True, help_text='Permitir registros via QR Code da igreja', verbose_name='QR Code Ativo'),
        ),
        migrations.AddField(
            model_name='church',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='QR Code gerado automaticamente para registro de visitantes na sede', null=True, upload_to='churches/qr_codes/', verbose_name='Imagem do QR Code'),
        ),
        migrations.AddField(
            model_name='church',
            name='qr_code_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para o QR Code da igreja (sede)', verbose_name='UUID do QR Code'),
        ),
        migrations.AddField(
            model_name='church',
            name='total_visitors_registered',
            field=models.PositiveIntegerField(default=0, help_text='Contador de visitantes via QR Code', verbose_name='Total de Visitantes Registrados'),
        ),
        # Gerar UUIDs únicos para igrejas existentes
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        # Adicionar constraint de unicidade após popular os dados
        migrations.AlterField(
            model_name='church',
            name='qr_code_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para o QR Code da igreja (sede)', unique=True, verbose_name='UUID do QR Code'),
        ),
    ]
