# Generated by Django 5.2.3 on 2025-10-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0005_move_church_qr_to_main_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='qr_code_active',
        ),
        migrations.RemoveField(
            model_name='church',
            name='qr_code_image',
        ),
        migrations.RemoveField(
            model_name='church',
            name='qr_code_uuid',
        ),
    ]
