# Generated by Django 5.2.3 on 2025-09-06 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_alter_church_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('title', models.CharField(help_text='Título curto do pedido (ex: Saúde da minha mãe)', max_length=100, verbose_name='Título')),
                ('content', models.TextField(help_text='Descrição detalhada do pedido', max_length=1000, verbose_name='Conteúdo')),
                ('category', models.CharField(choices=[('personal', 'Pessoal'), ('family', 'Família'), ('health', 'Saúde'), ('finance', 'Finanças'), ('work', 'Trabalho'), ('studies', 'Estudos'), ('marriage', 'Matrimonial'), ('conversion', 'Conversão'), ('missions', 'Missões'), ('travel', 'Viagem'), ('church', 'Igreja'), ('thanksgiving', 'Ação de Graças'), ('nation', 'Nação'), ('growth', 'Crescimento')], default='personal', max_length=20, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('answered', 'Respondido'), ('closed', 'Fechado'), ('private', 'Privado')], default='active', max_length=20, verbose_name='Status')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Se verdadeiro, o nome do autor não será exibido', verbose_name='Pedido Anônimo')),
                ('allow_visit', models.BooleanField(default=False, help_text='Permitir que membros ofereçam visitas', verbose_name='Permitir Visita')),
                ('allow_contact', models.BooleanField(default=False, help_text='Permitir que membros entrem em contato', verbose_name='Permitir Contato')),
                ('publish_on_wall', models.BooleanField(default=True, help_text='Publicar no mural da igreja', verbose_name='Publicar no Mural')),
                ('image', models.ImageField(blank=True, help_text='Imagem opcional para o pedido', null=True, upload_to='prayer_requests/%Y/%m/', verbose_name='Imagem')),
                ('answered_at', models.DateTimeField(blank=True, help_text='Data em que o pedido foi marcado como respondido', null=True, verbose_name='Data da Resposta')),
                ('answer_testimony', models.TextField(blank=True, help_text='Testemunho de como a oração foi respondida', verbose_name='Testemunho de Resposta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('church', models.ForeignKey(help_text='Igreja do autor do pedido', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='churches.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Pedido de Oração',
                'verbose_name_plural': 'Pedidos de Oração',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('content', models.TextField(help_text='Mensagem de apoio e encorajamento', max_length=500, verbose_name='Mensagem')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Se verdadeiro, o nome do autor não será exibido', verbose_name='Mensagem Anônima')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_messages', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_messages', to='prayers.prayerrequest', verbose_name='Pedido de Oração')),
            ],
            options={
                'verbose_name': 'Mensagem de Apoio',
                'verbose_name_plural': 'Mensagens de Apoio',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('is_praying', models.BooleanField(default=True, help_text='Se o usuário está orando por este pedido', verbose_name='Está Orando')),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_responses', to='prayers.prayerrequest', verbose_name='Pedido de Oração')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_responses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta de Oração',
                'verbose_name_plural': 'Respostas de Oração',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['church', '-created_at'], name='prayers_pra_church__6267bb_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['category', '-created_at'], name='prayers_pra_categor_f354c9_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['status', '-created_at'], name='prayers_pra_status_205703_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['author', '-created_at'], name='prayers_pra_author__3cb07f_idx'),
        ),
        migrations.AddIndex(
            model_name='prayermessage',
            index=models.Index(fields=['prayer_request', 'created_at'], name='prayers_pra_prayer__ec18bb_idx'),
        ),
        migrations.AddIndex(
            model_name='prayermessage',
            index=models.Index(fields=['author', '-created_at'], name='prayers_pra_author__3e249b_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerresponse',
            index=models.Index(fields=['prayer_request', '-created_at'], name='prayers_pra_prayer__d08d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerresponse',
            index=models.Index(fields=['user', '-created_at'], name='prayers_pra_user_id_7689d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prayerresponse',
            unique_together={('prayer_request', 'user')},
        ),
    ]
