# Generated by Django 5.1.4 on 2025-06-12 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("branches", "0001_initial"),
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchuser",
            name="church",
            field=models.ForeignKey(
                help_text="Igreja à qual o usuário pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="churches.church",
                verbose_name="Igreja",
            ),
        ),
        migrations.AddField(
            model_name="churchuser",
            name="managed_branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Filiais específicas que este usuário pode gerenciar",
                related_name="managers",
                to="branches.branch",
                verbose_name="Filiais Gerenciadas",
            ),
        ),
        migrations.AddField(
            model_name="churchuser",
            name="user",
            field=models.ForeignKey(
                help_text="Usuário do sistema",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="church_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Usuário relacionado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="churchuser",
            index=models.Index(
                fields=["user", "church"], name="accounts_ch_user_id_c50386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="churchuser",
            index=models.Index(
                fields=["church", "role"], name="accounts_ch_church__927d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="churchuser",
            index=models.Index(
                fields=["church", "is_active"], name="accounts_ch_church__a556a6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="churchuser",
            unique_together={("user", "church")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="accounts_us_user_id_806298_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["cpf"], name="accounts_us_cpf_39174e_idx"),
        ),
    ]
