# Generated by Django 5.2.3 on 2025-07-01 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                help_text="Data de nascimento do usuário",
                null=True,
                verbose_name="Data de Nascimento",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Não informado"),
                ],
                help_text="Gênero do usuário",
                max_length=1,
                null=True,
                verbose_name="Gênero",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                help_text="Telefone no formato (XX) XXXXX-XXXX",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve estar no formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX",
                        regex="^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$",
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
    ]
