# Generated by Django 5.0.6 on 2025-07-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_birth_date_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Indica se o usuário completou todas as etapas do cadastro.', verbose_name='Perfil Completo'),
        ),
    ] 