# Generated by Django 5.2.3 on 2025-07-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_add_is_profile_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Não informar"),
                ],
                max_length=1,
                null=True,
                verbose_name="Gênero",
            ),
        ),
    ]
