# Generated by Django 5.2.3 on 2025-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Biografia ou descrição do usuário",
                verbose_name="Bio",
            ),
        ),
    ]
