# Generated by Django 5.2.3 on 2025-07-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_fix_bio_field_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="gender",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Não informado"),
                ],
                help_text="Gênero do usuário",
                max_length=1,
                null=True,
                verbose_name="Gênero",
            ),
        ),
    ]
