# Generated by Django 5.2.3 on 2025-08-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchuser',
            name='can_create_churches',
            field=models.BooleanField(default=False, help_text='Se pode criar novas igrejas na denominação', verbose_name='Criar Igrejas'),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='can_manage_church_admins',
            field=models.BooleanField(default=False, help_text='Se pode definir administradores de igrejas', verbose_name='Gerenciar Admins de Igreja'),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='can_manage_denomination',
            field=models.BooleanField(default=False, help_text='Se pode gerenciar configurações da denominação', verbose_name='Gerenciar Denominação'),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='can_view_financial_reports',
            field=models.BooleanField(default=False, help_text='Se pode ver relatórios financeiros consolidados', verbose_name='Ver Relatórios Financeiros'),
        ),
    ]
