# Generated by Django 5.2.3 on 2025-08-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_churchuser_can_create_churches_and_more'),
    ]

    operations = [
    ]
