# Generated by Django 5.2.3 on 2025-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250831_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Básico'), ('professional', 'Profissional'), ('enterprise', 'Enterprise'), ('denomination', 'Denominação')], help_text='Plano de assinatura SaaS (apenas para administradores de denominação)', max_length=20, null=True, verbose_name='Plano de Assinatura'),
        ),
    ]
