# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20241031_1234'),  # Ajustar para a migração anterior correta
    ]

    operations = [
        # Migração vazia - apenas para manter a numeração sequencial
        # Se necessário, adicione operações específicas aqui
    ]