# Generated by Django 5.2.3 on 2025-08-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250831_0914'),
    ]

    operations = [
        # No-op migration - fields already removed or never existed
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
