# Generated by Django 5.2.3 on 2025-08-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250831_0914'),
    ]

    operations = [
        # Migração vazia - os campos já foram removidos em migrações anteriores
        # ou nunca existiram no modelo atual
    ]
