# Generated by Django 5.2.3 on 2025-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchuser',
            name='can_create_churches',
        ),
        migrations.RemoveField(
            model_name='churchuser',
            name='can_manage_church_admins',
        ),
        migrations.RemoveField(
            model_name='churchuser',
            name='can_manage_denomination',
        ),
        migrations.RemoveField(
            model_name='churchuser',
            name='can_view_financial_reports',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Básico'), ('professional', 'Profissional'), ('enterprise', 'Enterprise'), ('denomination', 'Denominação')], help_text='Plano de assinatura SaaS (apenas para administradores de denominação)', max_length=20, null=True, verbose_name='Plano de Assinatura'),
        ),
    ]
