# Generated by Django 5.2.3 on 2025-08-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_extra_church_user_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchuser',
            name='can_create_churches',
        ),
        migrations.RemoveField(
            model_name='churchuser',
            name='can_manage_church_admins',
        ),
        migrations.RemoveField(
            model_name='churchuser',
            name='can_manage_denomination',
        ),
        migrations.RemoveField(
            model_name='churchuser',
            name='can_view_financial_reports',
        ),
    ]
