# Generated by Django 5.2.3 on 2025-09-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_churchuser_can_create_churches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchuser',
            name='is_user_active_church',
            field=models.BooleanField(default=False, help_text='Se esta é a igreja ativa atual do usuário (para admins de denominação)', verbose_name='Igreja Ativa do Usuário'),
        ),
    ]
