# Generated by Django 5.2.3 on 2025-10-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_convert_denomination_admin_to_church_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Rua/Avenida do usuário', max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='complement',
            field=models.CharField(blank=True, help_text='Complemento do endereço', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Bairro', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, help_text='Número do endereço', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='Estado (UF)', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, help_text='CEP do endereço do usuário', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='churchuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('church_admin', 'Administrador da Igreja'), ('pastor', 'Pastor'), ('secretary', 'Secretário(a)'), ('leader', 'Líder'), ('member', 'Membro'), ('read_only', 'Somente Leitura')], default='member', help_text='Papel do usuário nesta igreja', max_length=20, verbose_name='Papel'),
        ),
    ]
