# Generated by Django 5.2.3 on 2025-10-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_address_userprofile_city_and_more'),
        ('denominations', '0002_alter_denomination_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intended_denomination',
            field=models.ForeignKey(blank=True, help_text='Denominação escolhida pelo usuário no cadastro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_users', to='denominations.denomination', verbose_name='Denominação Pretendida'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intended_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Administrador'), ('church_admin', 'Administrador da Igreja'), ('pastor', 'Pastor'), ('secretary', 'Secretário(a)'), ('leader', 'Líder'), ('member', 'Membro'), ('read_only', 'Somente Leitura')], help_text='Papel que o usuário terá quando criar/vincular a uma igreja', max_length=20, null=True, verbose_name='Papel Pretendido'),
        ),
    ]
