# Generated by Django 5.2.3 on 2025-10-23 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_intended_denomination_and_more'),
        ('branches', '0004_branch_is_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchuser',
            name='active_branch',
            field=models.ForeignKey(blank=True, help_text='Filial padrão utilizada nas operações do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='branches.branch', verbose_name='Filial Ativa'),
        ),
    ]
