# Generated by Django 5.2.3 on 2025-11-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_churchuser_active_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_active_email',
        ),
    ]
