# Generated by Django 5.2.3 on 2025-11-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_unique_email_constraint'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS unique_active_email;',
            reverse_sql='CREATE UNIQUE INDEX unique_active_email ON accounts_customuser (email) WHERE is_active = true;'
        ),
    ]
