# Generated by Django 5.2.3 on 2025-11-07 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_unique_email_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('token', models.CharField(help_text='Token único para redefinição de senha', max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(help_text='Data e hora de expiração do token', verbose_name='Expira em')),
                ('is_used', models.BooleanField(default=False, help_text='Indica se o token já foi utilizado', verbose_name='Utilizado')),
                ('used_at', models.DateTimeField(blank=True, help_text='Data e hora em que o token foi utilizado', null=True, verbose_name='Utilizado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de onde foi solicitada a redefinição', null=True, verbose_name='Endereço IP')),
                ('user', models.ForeignKey(help_text='Usuário que solicitou a redefinição', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Redefinição de Senha',
                'verbose_name_plural': 'Tokens de Redefinição de Senha',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_pa_token_affdf2_idx'), models.Index(fields=['user', 'is_used'], name='accounts_pa_user_id_023f8d_idx'), models.Index(fields=['expires_at'], name='accounts_pa_expires_01b447_idx')],
            },
        ),
    ]
