# Generated by Django 5.2.3 on 2025-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='total_visitors_registered',
            field=models.PositiveIntegerField(default=0, help_text='Contador de visitantes registrados via QR code', verbose_name='Total de Visitantes Registrados'),
        ),
    ]
