# Generated by Django 5.2.3 on 2025-10-23 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_is_headquarters'),
        ('churches', '0003_add_qr_code_to_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_headquarters', True)), fields=('church',), name='unique_headquarters_per_church'),
        ),
    ]
