# Generated by Django 5.2.3 on 2025-08-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('member', 'Membro'), ('deacon', 'Diácono'), ('deaconess', 'Diaconisa'), ('elder', 'Presbítero'), ('evangelist', 'Evangelista'), ('pastor', 'Pastor'), ('female_pastor', 'Pastora'), ('missionary', 'Missionário'), ('female_missionary', 'Missionária'), ('leader', 'Líder'), ('cooperator', 'Cooperador(ra)'), ('auxiliary', 'Auxiliar')], default='member', help_text='Função/cargo ministerial', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Se o status está ativo/inativo', verbose_name='Ativo/Inativo')),
                ('ordination_date', models.DateField(blank=True, help_text='Data de ordenação ministerial (se aplicável)', null=True, verbose_name='Data de Ordenação')),
                ('termination_date', models.DateField(blank=True, help_text='Data de término do status (se aplicável)', null=True, verbose_name='Data de Término')),
                ('observation', models.TextField(blank=True, help_text='Observações sobre o status', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_statuses', to='members.member')),
            ],
        ),
    ]
