# Generated by Django 5.2.3 on 2025-08-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_gender'),
        ('members', '0002_membershipstatus'),
    ]

    operations = [
    ]
