# Generated by Django 5.2.3 on 2025-08-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_migrate_ministerial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipstatus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Status de Membresia', 'verbose_name_plural': 'Status de Membresia'},
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='id_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_statuses', to='members.member', verbose_name='Membro'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='status',
            field=models.CharField(choices=[('member', 'Membro'), ('deacon', 'Diácono'), ('deaconess', 'Diaconisa'), ('elder', 'Presbítero'), ('evangelist', 'Evangelista'), ('pastor', 'Pastor'), ('female_pastor', 'Pastora'), ('missionary', 'Missionário'), ('female_missionary', 'Missionária'), ('leader', 'Líder'), ('cooperator', 'Cooperador(a)'), ('auxiliary', 'Auxiliar')], default='member', help_text='Função/cargo ministerial', max_length=20),
        ),
    ]
