# Generated by Django 5.2.3 on 2025-08-31 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse_is_member',
            field=models.BooleanField(default=False, help_text='Marcar se o cônjuge também é membro desta igreja', verbose_name='Cônjuge é Membro da Igreja'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_member',
            field=models.ForeignKey(blank=True, help_text='Selecionar o cônjuge se for membro da igreja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='members.member', verbose_name='Cônjuge (Membro)'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Nome completo do cônjuge (preencher se casado)', max_length=200, verbose_name='Nome do Cônjuge'),
        ),
    ]
