# Generated by Django 5.2.3 on 2025-08-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_add_spouse_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='spouse',
        ),
    ]
