# Generated by Django 5.2.3 on 2025-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_old_spouse_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='children_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de filhos (opcional)', null=True, verbose_name='Quantidade de Filhos'),
        ),
    ]
