# Generated by Django 5.2.3 on 2025-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_add_children_count_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Nome completo do cônjuge (preencher se casado)', max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
    ]
