# Generated by Django 5.2.3 on 2025-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_fix_spouse_name_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='complement',
            field=models.CharField(blank=True, help_text='Complemento (apartamento, bloco, etc.)', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='member',
            name='number',
            field=models.CharField(blank=True, help_text='Número da residência', max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço (rua, avenida, etc.)', verbose_name='Endereço'),
        ),
    ]
