# Generated by Django 5.2.3 on 2025-09-05 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_add_ministerial_function_log_simple'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membershipstatuslog',
            index=models.Index(fields=['member', '-created_at'], name='members_mem_member__36dca2_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipstatuslog',
            index=models.Index(fields=['new_status', '-created_at'], name='members_mem_new_sta_7fe178_idx'),
        ),
        migrations.AddIndex(
            model_name='ministerialfunctionlog',
            index=models.Index(fields=['member', '-effective_date'], name='members_min_member__94ba5d_idx'),
        ),
        migrations.AddIndex(
            model_name='ministerialfunctionlog',
            index=models.Index(fields=['new_function', '-effective_date'], name='members_min_new_fun_75ce78_idx'),
        ),
    ]
