# Generated by Django 5.2.3 on 2025-09-09 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_activities__branch__f60ef3_idx_and_more'),
        ('churches', '0002_alter_church_cnpj'),
        ('members', '0012_membershipstatuslog_members_mem_member__36dca2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('status', models.CharField(choices=[('member', 'Membro'), ('deacon', 'Diácono'), ('deaconess', 'Diaconisa'), ('elder', 'Presbítero'), ('evangelist', 'Evangelista'), ('pastor', 'Pastor'), ('missionary', 'Missionário'), ('leader', 'Líder'), ('cooperator', 'Cooperador'), ('auxiliary', 'Auxiliar')], help_text='Status ministerial específico', max_length=100, verbose_name='Status')),
                ('ordination_date', models.DateField(blank=True, help_text='Data de início do status', null=True, verbose_name='Data de Ordenação')),
                ('termination_date', models.DateField(blank=True, help_text='Data de fim do status (vazio se ainda ativo)', null=True, verbose_name='Data de Término')),
                ('observation', models.TextField(blank=True, help_text='Observações sobre este status', verbose_name='Observações')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_statuses', to='members.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Status de Membresia',
                'verbose_name_plural': 'Status de Membresia',
                'ordering': ['-ordination_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershipstatus',
            index=models.Index(fields=['member', '-ordination_date'], name='members_mem_member__cba717_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipstatus',
            index=models.Index(fields=['status', '-ordination_date'], name='members_mem_status_28fd50_idx'),
        ),
    ]