# Generated by Django 5.2.3 on 2025-09-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_membershipstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('transferred', 'Transferido'), ('disciplined', 'Disciplinado'), ('deceased', 'Falecido')], default='active', help_text='Status atual da membresia', max_length=20, verbose_name='Status de Membresia'),
        ),
    ]
