# Generated by Django 5.2.3 on 2025-10-05 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_activities__branch__f60ef3_idx_and_more'),
        ('churches', '0002_alter_church_cnpj'),
        ('members', '0016_make_cpf_phone_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministerialfunctionlog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='ministerialfunctionlog',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_is_member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.ForeignKey(blank=True, help_text='Cônjuge (se for membro da igreja)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='members.member', verbose_name='Cônjuge'),
        ),
        migrations.AlterField(
            model_name='membershipstatuslog',
            name='new_status',
            field=models.CharField(help_text='Novo status do membro', max_length=20, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='membershipstatuslog',
            name='old_status',
            field=models.CharField(help_text='Status anterior do membro', max_length=20, verbose_name='Status Anterior'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['conversion_date'], name='members_mem_convers_b48af6_idx'),
        ),
        migrations.DeleteModel(
            name='MinisterialFunctionLog',
        ),
    ]
