# Generated by Django 5.2.3 on 2025-10-23 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_activities__branch__f60ef3_idx_and_more'),
        ('branches', '0004_branch_is_headquarters'),
        ('churches', '0003_add_qr_code_to_church'),
        ('members', '0017_remove_ministerialfunctionlog_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Filial de referência do membro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='branches.branch', verbose_name='Filial'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'branch'], name='members_mem_church__ce62e1_idx'),
        ),
    ]
