# Generated by Django 5.2.3 on 2025-10-23 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_member_branch_member_members_mem_church__ce62e1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterialFunctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('function', models.CharField(choices=[('member', 'Membro'), ('deacon', 'Diácono'), ('deaconess', 'Diaconisa'), ('elder', 'Presbítero'), ('evangelist', 'Evangelista'), ('pastor', 'Pastor'), ('missionary', 'Missionário'), ('leader', 'Líder'), ('cooperator', 'Cooperador'), ('auxiliary', 'Auxiliar')], help_text='Função ministerial atribuída', max_length=100, verbose_name='Função')),
                ('start_date', models.DateField(help_text='Data de início da função', verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, help_text='Data de término da função (vazio se atual)', null=True, verbose_name='Data de Fim')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a mudança de função', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Histórico de Função Ministerial',
                'verbose_name_plural': 'Histórico de Funções Ministeriais',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='members_mem_convers_b48af6_idx',
        ),
        migrations.RemoveField(
            model_name='member',
            name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ordination_date',
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('transferred', 'Transferido'), ('disciplined', 'Disciplinado'), ('deceased', 'Falecido')], help_text='Status de membresia', max_length=100, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ministerialfunctionhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerial_function_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='ministerialfunctionhistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministerial_function_history', to='members.member', verbose_name='Membro'),
        ),
        migrations.AddIndex(
            model_name='ministerialfunctionhistory',
            index=models.Index(fields=['member', '-start_date'], name='members_min_member__a8f6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ministerialfunctionhistory',
            index=models.Index(fields=['function', '-start_date'], name='members_min_functio_26beed_idx'),
        ),
        migrations.AddConstraint(
            model_name='ministerialfunctionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('member',), name='unique_current_ministerial_function_per_member'),
        ),
    ]
