# Generated by Django 5.2.3 on 2025-10-28 14:06

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_membershipstatus_branch_and_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='member',
            new_name='members_mem_members_931ae5_idx',
            old_name='members_mem_members_ba5341_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatus',
            new_name='members_mem_member__77d5d5_idx',
            old_name='members_mem_member__eff_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatus',
            new_name='members_mem_status_0ca681_idx',
            old_name='members_mem_status_eff_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatus',
            new_name='members_mem_branch__83f98d_idx',
            old_name='members_mem_branch_idx',
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do membro (opcional)', max_length=14, null=True, validators=[apps.core.models.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_end_date',
            field=models.DateField(blank=True, help_text='Data de término da membresia (se desligado)', null=True, verbose_name='Fim da Membresia'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(blank=True, help_text='Data de início da membresia (compatível com membership_date)', null=True, verbose_name='Início da Membresia'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Data de início do status', null=True, verbose_name='Data Efetiva'),
        ),
    ]
