# Generated by Django 5.2.3 on 2025-11-05 00:36

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_rename_is_headquarters_to_is_main'),
        ('members', '0025_membershipstatus_branch_and_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('previous_membership_start_date', models.DateField(blank=True, help_text='Quando o membro entrou na congregação de origem', null=True, verbose_name='Data Início na Congregação Anterior')),
                ('transfer_date', models.DateField(help_text='Data em que a transferência foi realizada', verbose_name='Data da Transferência')),
                ('reason', models.TextField(blank=True, help_text='Motivo da transferência entre congregações', verbose_name='Motivo')),
                ('transfer_type', models.CharField(choices=[('same_church', 'Entre congregações da mesma igreja'), ('different_church', 'Entre igrejas diferentes (mesma denominação)')], default='same_church', help_text='Indica se a transferência foi dentro da mesma igreja ou entre igrejas', max_length=20, verbose_name='Tipo de Transferência')),
            ],
            options={
                'verbose_name': 'Log de Transferência entre Congregações',
                'verbose_name_plural': 'Logs de Transferências entre Congregações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='members_mem_members_931ae5_idx',
            old_name='members_mem_members_ba5341_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatus',
            new_name='members_mem_member__77d5d5_idx',
            old_name='members_mem_member__eff_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatus',
            new_name='members_mem_status_0ca681_idx',
            old_name='members_mem_status_eff_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatus',
            new_name='members_mem_branch__83f98d_idx',
            old_name='members_mem_branch_idx',
        ),
        migrations.AddField(
            model_name='member',
            name='first_membership_date',
            field=models.DateField(blank=True, help_text='Data original de entrada na denominação/igreja (nunca muda após criação)', null=True, verbose_name='Primeira Membresia'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do membro (opcional)', max_length=14, null=True, validators=[apps.core.models.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_end_date',
            field=models.DateField(blank=True, help_text='Data de término da membresia (se desligado)', null=True, verbose_name='Fim da Membresia'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(blank=True, help_text='Data de início na congregação atual', null=True, verbose_name='Início da Membresia'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Data de início do status', null=True, verbose_name='Data Efetiva'),
        ),
        migrations.AddField(
            model_name='branchtransferlog',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_transferred_out', to='branches.branch', verbose_name='Congregação de Origem'),
        ),
        migrations.AddField(
            model_name='branchtransferlog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfer_history', to='members.member', verbose_name='Membro'),
        ),
        migrations.AddField(
            model_name='branchtransferlog',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_transferred_in', to='branches.branch', verbose_name='Congregação de Destino'),
        ),
        migrations.AddField(
            model_name='branchtransferlog',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transfers_made', to=settings.AUTH_USER_MODEL, verbose_name='Transferido por'),
        ),
        migrations.AddIndex(
            model_name='branchtransferlog',
            index=models.Index(fields=['member', '-created_at'], name='members_bra_member__47244c_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransferlog',
            index=models.Index(fields=['from_branch', '-created_at'], name='members_bra_from_br_4093c5_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransferlog',
            index=models.Index(fields=['to_branch', '-created_at'], name='members_bra_to_bran_e2b012_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransferlog',
            index=models.Index(fields=['transfer_date'], name='members_bra_transfe_737262_idx'),
        ),
    ]
