# Generated by Django 5.1.4 on 2025-06-12 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("churches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do recurso (ex: Microfone sem fio)",
                        max_length=100,
                        verbose_name="Nome do Recurso",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do recurso",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("audio", "Áudio"),
                            ("video", "Vídeo"),
                            ("lighting", "Iluminação"),
                            ("furniture", "Mobiliário"),
                            ("instrument", "Instrumento"),
                            ("tech", "Tecnologia"),
                            ("decoration", "Decoração"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        help_text="Categoria do recurso",
                        max_length=30,
                        verbose_name="Tipo de Recurso",
                    ),
                ),
                (
                    "quantity_available",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantidade disponível para uso",
                        verbose_name="Quantidade Disponível",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityResourceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "quantity_requested",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade Solicitada"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("denied", "Negado"),
                            ("allocated", "Alocado"),
                            ("returned", "Devolvido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
            ],
            options={
                "verbose_name": "Solicitação de Recurso",
                "verbose_name_plural": "Solicitações de Recursos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do ministério (ex: Louvor, Jovens)",
                        max_length=100,
                        verbose_name="Nome do Ministério",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição e propósito do ministério",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Cor hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Se aparece publicamente para visitantes",
                        verbose_name="Público",
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Total de Membros",
                    ),
                ),
                (
                    "total_activities",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Total de Atividades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ministério",
                "verbose_name_plural": "Ministérios",
                "ordering": ["church", "name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da atividade (ex: Culto de Domingo)",
                        max_length=200,
                        verbose_name="Nome da Atividade",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da atividade",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("worship", "Culto"),
                            ("prayer", "Oração"),
                            ("study", "Estudo Bíblico"),
                            ("cell", "Célula"),
                            ("rehearsal", "Ensaio"),
                            ("meeting", "Reunião"),
                            ("event", "Evento"),
                            ("conference", "Conferência"),
                            ("seminar", "Seminário"),
                            ("training", "Treinamento"),
                            ("outreach", "Evangelismo"),
                            ("service", "Ação Social"),
                            ("youth", "Jovens"),
                            ("children", "Infantil"),
                            ("other", "Outro"),
                        ],
                        default="worship",
                        help_text="Tipo da atividade",
                        max_length=30,
                        verbose_name="Tipo de Atividade",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="Data e hora de início da atividade",
                        verbose_name="Data/Hora de Início",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="Data e hora de término da atividade",
                        verbose_name="Data/Hora de Término",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Se a atividade se repete",
                        verbose_name="Atividade Recorrente",
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("biweekly", "Quinzenal"),
                            ("monthly", "Mensal"),
                            ("custom", "Personalizado"),
                        ],
                        help_text="Como a atividade se repete",
                        max_length=20,
                        verbose_name="Padrão de Recorrência",
                    ),
                ),
                (
                    "recurrence_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Data limite para atividade recorrente",
                        null=True,
                        verbose_name="Fim da Recorrência",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Local específico (se diferente da filial)",
                        max_length=200,
                        verbose_name="Local",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limite de participantes (deixe vazio para ilimitado)",
                        null=True,
                        verbose_name="Máximo de Participantes",
                    ),
                ),
                (
                    "requires_registration",
                    models.BooleanField(
                        default=False,
                        help_text="Se requer inscrição prévia",
                        verbose_name="Requer Inscrição",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Se aparece publicamente",
                        verbose_name="Público",
                    ),
                ),
                (
                    "participants_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Participantes Confirmados",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações internas sobre a atividade",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Filial onde ocorre a atividade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="branches.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        help_text="Igreja responsável",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="churches.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pessoa responsável pela atividade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Inscrito"),
                            ("confirmed", "Confirmado"),
                            ("present", "Presente"),
                            ("absent", "Ausente"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="registered",
                        help_text="Status da participação",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Inscrição"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre a participação",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="activities.activity",
                        verbose_name="Atividade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante de Atividade",
                "verbose_name_plural": "Participantes de Atividades",
                "ordering": ["-registration_date"],
            },
        ),
    ]
