# Generated by Django 5.1.4 on 2025-06-12 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("churches", "0001_initial"),
        ("members", "0001_initial"),
        ("visitors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityparticipant",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_participations",
                to="members.member",
                verbose_name="Membro",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_participations",
                to="visitors.visitor",
                verbose_name="Visitante",
            ),
        ),
        migrations.AddField(
            model_name="activityresource",
            name="church",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_resources",
                to="churches.church",
                verbose_name="Igreja",
            ),
        ),
        migrations.AddField(
            model_name="activityresource",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="activityresourcerequest",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_requests",
                to="activities.activity",
                verbose_name="Atividade",
            ),
        ),
        migrations.AddField(
            model_name="activityresourcerequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitado por",
            ),
        ),
        migrations.AddField(
            model_name="activityresourcerequest",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="activities.activityresource",
                verbose_name="Recurso",
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="church",
            field=models.ForeignKey(
                help_text="Igreja à qual o ministério pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ministries",
                to="churches.church",
                verbose_name="Igreja",
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                help_text="Líder responsável pelo ministério",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_ministries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Líder",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="ministry",
            field=models.ForeignKey(
                help_text="Ministério responsável",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="activities.ministry",
                verbose_name="Ministério",
            ),
        ),
        migrations.AddIndex(
            model_name="activityparticipant",
            index=models.Index(
                fields=["activity", "status"], name="activities__activit_9717d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityparticipant",
            index=models.Index(
                fields=["member"], name="activities__member__ce74ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityparticipant",
            index=models.Index(
                fields=["visitor"], name="activities__visitor_d3649e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "member"), ("activity", "visitor")},
        ),
        migrations.AlterUniqueTogether(
            name="activityresource",
            unique_together={("church", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="activityresourcerequest",
            unique_together={("activity", "resource")},
        ),
        migrations.AddIndex(
            model_name="ministry",
            index=models.Index(
                fields=["church", "name"], name="activities__church__bda137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ministry",
            index=models.Index(
                fields=["church", "is_active"], name="activities__church__2282e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ministry",
            unique_together={("church", "name")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["church", "-start_datetime"],
                name="activities__church__644cc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["branch", "-start_datetime"],
                name="activities__branch__f60ef3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["ministry", "-start_datetime"],
                name="activities__ministr_6fd00c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_type"], name="activities__activit_8e7970_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["start_datetime"], name="activities__start_d_5cbe5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["is_recurring"], name="activities__is_recu_2e4401_idx"
            ),
        ),
    ]
