# Generated by Django 5.2.3 on 2025-07-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__branch__f60ef3_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__ministr_6fd00c_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__activit_8e7970_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__start_d_5cbe5c_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__is_recu_2e4401_idx",
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
