# Generated by Django 5.1.4 on 2025-06-12 00:01

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Denomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Assembleia de Deus Regional São Paulo",
                        max_length=200,
                        verbose_name="Nome da Denominação",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Ex: AD São Paulo",
                        max_length=50,
                        verbose_name="Nome Curto",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da denominação, história, missão",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-mail oficial da denominação",
                        max_length=254,
                        verbose_name="E-mail principal",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Telefone da sede no formato (XX) XXXXX-XXXX",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefone deve estar no formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX",
                                regex="^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Site oficial da denominação",
                        verbose_name="Website",
                    ),
                ),
                (
                    "headquarters_address",
                    models.TextField(
                        help_text="Endereço completo da sede da denominação",
                        verbose_name="Endereço da Sede",
                    ),
                ),
                (
                    "headquarters_city",
                    models.CharField(max_length=100, verbose_name="Cidade da Sede"),
                ),
                (
                    "headquarters_state",
                    models.CharField(
                        help_text="Sigla do estado (ex: SP, RJ, MG)",
                        max_length=2,
                        verbose_name="Estado da Sede",
                    ),
                ),
                (
                    "headquarters_zipcode",
                    models.CharField(
                        help_text="CEP no formato XXXXX-XXX",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve estar no formato: XXXXX-XXX",
                                regex="^\\d{5}-\\d{3}$",
                            )
                        ],
                        verbose_name="CEP da Sede",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ da denominação (se aplicável)",
                        max_length=18,
                        null=True,
                        unique=True,
                        validators=[apps.core.models.validate_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo oficial da denominação",
                        null=True,
                        upload_to="denominations/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "total_churches",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Total de Igrejas",
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="Total de Membros",
                    ),
                ),
                (
                    "administrator",
                    models.ForeignKey(
                        help_text="Usuário que criou e administra esta denominação",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administered_denominations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrador Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denominação",
                "verbose_name_plural": "Denominações",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="denominatio_name_29951e_idx"),
                    models.Index(
                        fields=["administrator"], name="denominatio_adminis_f6700d_idx"
                    ),
                    models.Index(
                        fields=["headquarters_state"],
                        name="denominatio_headqua_17dada_idx",
                    ),
                ],
            },
        ),
    ]
