# Generated by Django 5.2.3 on 2025-09-05 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denominations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomination',
            name='administrator',
            field=models.ForeignKey(help_text='Usuário que criou e administra esta denominação. Dono da Conta.', on_delete=django.db.models.deletion.PROTECT, related_name='administered_denominations', to=settings.AUTH_USER_MODEL, verbose_name='Administrador Principal'),
        ),
    ]
