# Generated by Django 5.2.3 on 2025-10-27 13:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denominations', '0002_alter_denomination_administrator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='allows_visitor_registration',
            field=models.BooleanField(default=True, help_text='Default da denominação para permitir registro de visitantes', verbose_name='Permite Registro de Visitantes'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='max_branches',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de filiais por denominação (agregado). 0 = ilimitado', verbose_name='Limite de Filiais'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='max_churches',
            field=models.PositiveIntegerField(default=1, help_text='Máximo de igrejas permitidas. 0 = ilimitado', verbose_name='Limite de Igrejas'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='max_members',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de membros agregados. 0 = ilimitado', verbose_name='Limite de Membros'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='Data de término da assinatura', null=True, verbose_name='Fim da Assinatura'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Básico'), ('professional', 'Profissional'), ('enterprise', 'Enterprise'), ('denomination', 'Denominação')], default='basic', help_text='Plano SaaS contratado para a denominação', max_length=20, verbose_name='Plano de Assinatura'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='subscription_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data de início da assinatura', verbose_name='Início da Assinatura'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('suspended', 'Suspensa'), ('trial', 'Período de teste')], default='trial', help_text='Status atual da assinatura', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='total_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Total agregado de visitantes em todas as igrejas', verbose_name='Total de Visitantes'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='total_visitors_registered',
            field=models.PositiveIntegerField(default=0, help_text='Total agregado de registros via QR code', verbose_name='Total de Visitantes Registrados'),
        ),
        migrations.AddField(
            model_name='denomination',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='Data de fim do trial, quando em período de teste', null=True, verbose_name='Fim do Período de Teste'),
        ),
        migrations.AddIndex(
            model_name='denomination',
            index=models.Index(fields=['subscription_status'], name='denominatio_subscri_00f803_idx'),
        ),
    ]
